### ISSUE TITLE
Assignment parameter with an object inside of array keeps updating in the plan

### ISSUE THREAD

**Issue by JCRL21** [Azure/enterprise-azure-policy-as-code#858]
**Describe the bug**
The assignment parameter tagvalues has type Array which consist of an object. This setup worked fine before converting to EPaC and the deployment of the policy and assignment also works fine with EPaC, however the EPaC plan always wants to update this assignment afterwards. 
There is some kind of mismatch between the assignment parameters in the portal and the parameter in my code, when I have an Array with an object inside. The pictures show my parameter setup in the code and the portal, which shouldn't update. I have tried swapping positions of the keys in the object.

![Image](https://github.com/user-attachments/assets/18eedd32-6ae8-4b4d-9d49-f96d4210fbba)

![Image](https://github.com/user-attachments/assets/6bef9929-c4be-4034-9e0e-ce8387c5428a)

**To Reproduce**
To reproduce you need an assignment which has a parameter of type Array with an object inside. Then after deploying this assignment once, the plan always wants to update the assignment afterwards. 

**Expected behavior**
I expected the assignment to deploy once and not end in a infinite loop of updates in the plan.

**EPAC Version**
I use the lastest EPaC version each time i run the deploy pipeline.

**Comment by apybar** [comment]
@JCRL21 - I started experiencing this bug as well this week. Was going to open a ticket but thank you for doing so. I will figure out a path forward and try to get this resolved asap.

**Comment by anwather** [comment]
@apybar - it is probably something in `Confirm-ObjectValueEqualityDeep` function if you're looking.

**Comment by apybar** [comment]
This should be fixed in the next release (10.8.3)

**Comment by JCRL21** [comment]
I still have the same problem.

**Comment by anwather** [comment]
Is this with a built-in policy @JCRL21 ?

**Comment by JCRL21** [comment]
Yes the definition is a built-in policy with id: "/providers/Microsoft.Authorization/policyDefinitions/ba0df93e-e4ac-479a-aac2-134bbae39a1a" .
Then we use a custom setDefinition 

{
  "$schema": "https://raw.githubusercontent.com/Azure/enterprise-azure-policy-as-code/main/Schemas/policy-set-definition-schema.json",
  "name": "azure-update-manager-schedule",
  "properties": {
    "displayName": "Update Manager Schedules",
    "description": "This initiative configures Update Manger for tag based automated patching - both Arc and Azure virtual machines",
    "metadata": {
      "category": "Update Manager"
    },
    "parameters": {
      "maintenanceConfigurationResourceId": {
        "type": "String",
        "metadata": {
          "displayName": "Maintenance Configuration ARM ID",
          "description": "ARM ID of Maintenance Configuration which will be used for scheduling."
        },
        "defaultValue": ""
      },
      "operatingSystemTypes": {
        "type": "Array",
        "metadata": {
          "displayName": "Operating System types",
          "description": "The list of Operating System types from which machines need to be targeted."
        },
        "allowedValues": [
          "Windows",
          "Linux"
        ],
        "defaultValue": [
          "Windows",
          "Linux"
        ]
      },
      "tagValues": {
        "type": "Array",
        "metadata": {
          "displayName": "Tags on machines",
          "description": "The list of tags that need to matched for getting target machines."
        }
      },
      "tagOperator": {
        "type": "String",
        "metadata": {
          "displayName": "Tag operator",
          "description": "Matching condition for resource tags"
        },
        "allowedValues": [
          "All",
          "Any"
        ],
        "defaultValue": "Any"  
      }
    },
   "policyDefinitions": [
    {
      "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/ba0df93e-e4ac-479a-aac2-134bbae39a1a",
      "policyDefinitionReferenceId": "Schedule recurring updates using Azure Update Manager",
      "parameters": {
        "maintenanceConfigurationResourceId": {
          "value": "[parameters('maintenanceConfigurationResourceId')]"
        },
        "operatingSystemTypes": {
          "value": "[parameters('operatingSystemTypes')]"
        },
        "tagValues": {
          "value": "[parameters('tagValues')]"
        },
        "tagOperator": {
          "value": "[parameters('tagOperator')]"
        }
      }
    }
   ] 
  }
}

**Comment by anwather** [comment]
OK, I'll take another look but I thought I fixed this one. Did you update the module version?

**Comment by JCRL21** [comment]
The pipeline always uses the latest version by installing with "Install-Module EnterprisePolicyAsCode -Force"

**Comment by anwather** [comment]
No problems let me take a look tomorrow

**Comment by JCRL21** [comment]
Hi again. I am sorry to bring this issue up again, but our bug/issue is still present. 

I tried debugging the repository and came across somthing which could be the issue. 
In the function "Confirm-ParametersUsageMatches" the if statement on line 44 overwrites the parameter $definedParameterValue, with only the actaul string value from the hashtable. This gives the  $definedParameterValue the string value and not the hashtable values (see pictures below).




![Image](https://github.com/user-attachments/assets/2d3e315a-7e05-46c1-8973-b24cbddd60ac)

After $definedParameterValue = $definedParameter.value

![Image](https://github.com/user-attachments/assets/389b0438-82ae-479f-93b0-b2e7ff9484b5)


I tried removing the .value which solved the issue for the assignment parameters not updating anymore, however a lot of the policy sets updated instead.

**Comment by apybar** [comment]
@JCRL21 - I noticed it started doing it again within the last few weeks. We'll open this ticket back up and try to resolve asap.

**Comment by anwather** [comment]
@apybar - I think the issue is the parameter has keys called `key` and `value` - that function gets confused about it. Because it's a built-in I tried to do a use case specifically for that parameter but would definitely appreciate a fresh set of eyes on it.

**Comment by apybar** [comment]
@JCRL21 - I have this updated and it should be resolved on the next release.

**Comment by apybar** [comment]
@JCRL21   - should be resolved now in the now published v10.8.11
